import Foundation
import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// The real machine. Every AppKit / Accessibility / Carbon call the recorder used
/// to make inline now lives here, and only here.
///
/// This file is deliberately dumb — no policy, no filtering, no state beyond what
/// the OS hands back. Everything that *decides* something moved to
/// `RecordingService`, where it can be tested against a stub. If a bug is in this
/// file it is a wrong API call; if it is a bug about what mull records, it is not
/// in this file.
final class SystemCaptureEnvironment: CaptureEnvironment {

    var frontmostAppName: String? {
        NSWorkspace.shared.frontmostApplication?.localizedName
    }

    var frontmostBundleID: String? {
        NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    }

    var activeWindowTitle: String? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        let appElement = AXUIElementCreateApplication(app.processIdentifier)

        var windowRef: CFTypeRef?
        let result = AXUIElementCopyAttributeValue(
            appElement, kAXFocusedWindowAttribute as CFString, &windowRef
        )
        // Some apps answer kAXFocusedWindow with something that isn't an AXUIElement.
        // A force-cast crashes the whole recorder there, so verify the CF type first
        // (same guard as WindowTextCapture.focusedWindowText).
        guard result == .success, let window = windowRef,
              CFGetTypeID(window) == AXUIElementGetTypeID() else { return nil }
        let windowElement = unsafeDowncast(window as AnyObject, to: AXUIElement.self)

        var titleRef: CFTypeRef?
        AXUIElementCopyAttributeValue(windowElement, kAXTitleAttribute as CFString, &titleRef)
        return titleRef as? String
    }

    var clipboardChangeCount: Int { NSPasteboard.general.changeCount }

    var clipboardText: String? { NSPasteboard.general.string(forType: .string) }

    /// Pasteboard types by which the copying app itself says "do not keep this".
    ///
    /// `org.nspasteboard.ConcealedType` is the nspasteboard.org convention for a
    /// credential, and it is what 1Password, Bitwarden, Keychain Access and
    /// Secretive stamp on a copied secret. `TransientType` and
    /// `AutoGeneratedType` are the same convention's markers for a copy the user
    /// did not deliberately make. mull is, for this purpose, a clipboard manager,
    /// and these are the three a clipboard manager is asked not to retain.
    ///
    /// This list is an OS convention, not mull policy — the *decision* to honour it
    /// lives in `RecordingService.pollClipboard`, where it can be tested.
    private static let doNotStoreTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Asks for `types` and never for the payload: a concealed copy is recognised
    /// without the secret being read into this process at all.
    var clipboardIsMarkedDoNotStore: Bool {
        guard let types = NSPasteboard.general.types else { return false }
        return Self.doNotStoreTypes.contains(where: types.contains)
    }

    var isSecureInputEnabled: Bool { IsSecureEventInputEnabled() }
}
