import Foundation
import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// The real machine. Every AppKit / Accessibility / Carbon call the recorder used
/// to make inline now lives here, and only here.
///
/// This file is deliberately dumb — no policy, no filtering, no state beyond what
/// the OS hands back. Everything that *decides* something moved to
/// `RecordingService`, where it can be tested against a stub. If a bug is in this
/// file it is a wrong API call; if it is a bug about what mull records, it is not
/// in this file.
final class SystemCaptureEnvironment: CaptureEnvironment {

    var frontmostAppName: String? {
        NSWorkspace.shared.frontmostApplication?.localizedName
    }

    var frontmostBundleID: String? {
        NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    }

    /// The focused window's title, or the nearest thing to it the app will answer.
    ///
    /// `kAXFocusedWindow` alone was the whole implementation, and it is the attribute
    /// most likely to be missing: an app answers it only once its window has taken
    /// focus, and several answer it never. Preview is the cheap proof — it returns
    /// nothing for focused *or* main, and its title is sitting in `AXWindows[0]` the
    /// whole time. A nil here is not a cosmetic loss: `RecordingService.recordEvent`
    /// stamps every row with this title and derives the row's *entity* from it, so an
    /// app that never answers becomes hours of activity attributed to nothing, and
    /// junk projects named after the fallback text ("Firefox: unknown (20m9s)").
    ///
    /// Three attributes, cheapest first, first non-empty answer wins.
    var activeWindowTitle: String? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        let appElement = AXUIElementCreateApplication(app.processIdentifier)

        for attribute in [kAXFocusedWindowAttribute, kAXMainWindowAttribute] {
            if let title = Self.title(ofElementAt: attribute as CFString, in: appElement) {
                return title
            }
        }
        return Self.titleOfFirstWindow(in: appElement)
    }

    /// The title of the window an app names under `attribute`, if it names one.
    private static func title(ofElementAt attribute: CFString, in appElement: AXUIElement) -> String? {
        var windowRef: CFTypeRef?
        let result = AXUIElementCopyAttributeValue(appElement, attribute, &windowRef)
        // Some apps answer kAXFocusedWindow with something that isn't an AXUIElement.
        // A force-cast crashes the whole recorder there, so verify the CF type first
        // (same guard as WindowTextCapture.focusedWindowText).
        guard result == .success, let window = windowRef,
              CFGetTypeID(window) == AXUIElementGetTypeID() else { return nil }
        return title(of: unsafeDowncast(window as AnyObject, to: AXUIElement.self))
    }

    /// Last resort: the app's first window. An app with windows but no focused or
    /// main one still has a name for what is on screen.
    private static func titleOfFirstWindow(in appElement: AXUIElement) -> String? {
        var windowsRef: CFTypeRef?
        guard AXUIElementCopyAttributeValue(
                appElement, kAXWindowsAttribute as CFString, &windowsRef) == .success,
              let windows = windowsRef as? [AXUIElement],
              let first = windows.first else { return nil }
        return title(of: first)
    }

    /// An empty title is the same as no title to every caller here, so it is folded
    /// into nil once rather than checked at each of the three call sites.
    private static func title(of window: AXUIElement) -> String? {
        var titleRef: CFTypeRef?
        AXUIElementCopyAttributeValue(window, kAXTitleAttribute as CFString, &titleRef)
        guard let title = titleRef as? String, !title.isEmpty else { return nil }
        return title
    }

    var clipboardChangeCount: Int { NSPasteboard.general.changeCount }

    var clipboardText: String? { NSPasteboard.general.string(forType: .string) }

    /// Pasteboard types by which the copying app itself says "do not keep this".
    ///
    /// `org.nspasteboard.ConcealedType` is the nspasteboard.org convention for a
    /// credential, and it is what 1Password, Bitwarden, Keychain Access and
    /// Secretive stamp on a copied secret. `TransientType` and
    /// `AutoGeneratedType` are the same convention's markers for a copy the user
    /// did not deliberately make. mull is, for this purpose, a clipboard manager,
    /// and these are the three a clipboard manager is asked not to retain.
    ///
    /// This list is an OS convention, not mull policy — the *decision* to honour it
    /// lives in `RecordingService.pollClipboard`, where it can be tested.
    private static let doNotStoreTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Asks for `types` and never for the payload: a concealed copy is recognised
    /// without the secret being read into this process at all.
    var clipboardIsMarkedDoNotStore: Bool {
        guard let types = NSPasteboard.general.types else { return false }
        return Self.doNotStoreTypes.contains(where: types.contains)
    }

    var isSecureInputEnabled: Bool { IsSecureEventInputEnabled() }

    var focusedWindowBody: String? { WindowTextCapture.focusedWindowText() }

    /// `kCGAnyInputEventType` is `~0` — every input type at once, from the
    /// session-wide event stream, so input into other apps counts. This is the
    /// same clock display sleep and the screen saver run on, and unlike mull's own
    /// event tap it sees mouse movement and scrolling, so reading a long page
    /// without typing is correctly "present" rather than "away".
    ///
    /// `rawValue: ~0` is not one of the enum's cases. It survives the init on
    /// every SDK this has been run against, but a nil here must mean "present"
    /// rather than crash or silently stop capture.
    var secondsSinceUserInput: TimeInterval {
        guard let anyInput = CGEventType(rawValue: ~0) else { return 0 }
        return CGEventSource.secondsSinceLastEventType(.combinedSessionState, eventType: anyInput)
    }
}
