import SwiftUI

/// Files tab — Bear-inspired markdown viewer/editor.
///
/// Design principles (from Bear):
///   - Sidebar recedes. No borders, no cards. Just text.
///   - Editor is the star. Clean, warm, distraction-free.
///   - Typography creates hierarchy, not boxes.
///   - Tools appear on hover, hide when not needed.
///   - Warm grays, not cold. Comfortable to look at for hours.
struct FilesTab: View {
    @EnvironmentObject var appState: AppState
    @State private var selectedFile: DreamFile?
    @State private var fileTree: [DreamFileNode] = []
    @State private var editorContent: String = ""
    @State private var isDirty = false
    @State private var showNewNote = false
    @State private var newNoteName = ""
    @State private var isToolbarVisible = false

    private let dreamDir = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent("Dream")

    var body: some View {
        HSplitView {
            sidebar
                .frame(minWidth: 180, idealWidth: 210, maxWidth: 260)

            Divider()

            editor
                .frame(minWidth: 400)
        }
        .onAppear { refreshFileTree() }
    }

    // MARK: - Sidebar (Bear-style: quiet, text-only)

    private var sidebar: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Quiet header
            Text("Dream")
                .font(.system(size: 12, weight: .semibold))
                .foregroundStyle(.tertiary)
                .padding(.horizontal, DS.lg)
                .padding(.top, DS.md)
                .padding(.bottom, DS.sm)

            ScrollView {
                VStack(alignment: .leading, spacing: 0) {
                    // Core files (always visible, no folder)
                    ForEach(coreFiles, id: \.name) { file in
                        sidebarItem(file: file)
                    }

                    // Folders
                    ForEach(folders, id: \.name) { folder in
                        sidebarFolder(folder)
                    }
                }
                .padding(.horizontal, DS.sm)
            }

            Spacer()

            // New note — subtle, bottom of sidebar
            Button {
                showNewNote = true
            } label: {
                HStack(spacing: DS.sm) {
                    Image(systemName: "plus")
                        .font(.system(size: 10, weight: .medium))
                    Text("New Note")
                        .font(.system(size: 12))
                }
                .foregroundStyle(.tertiary)
                .padding(.horizontal, DS.lg)
                .padding(.vertical, DS.sm)
            }
            .buttonStyle(.plain)
            .sheet(isPresented: $showNewNote) {
                newNoteSheet
            }
        }
        .background(Color(.controlBackgroundColor).opacity(0.3))
    }

    // MARK: - Sidebar Items

    private func sidebarItem(file: DreamFile) -> some View {
        let isSelected = selectedFile?.path == file.path

        return Button {
            selectFile(file)
        } label: {
            HStack(spacing: DS.sm) {
                Circle()
                    .fill(fileAccent(file.name))
                    .frame(width: 6, height: 6)

                Text(displayName(file.name))
                    .font(.system(size: 13, weight: isSelected ? .medium : .regular))
                    .foregroundStyle(isSelected ? .primary : .secondary)
                    .lineLimit(1)

                Spacer()

                if file.isAutoGenerated {
                    Circle()
                        .fill(Color.accentColor.opacity(0.3))
                        .frame(width: 4, height: 4)
                }
            }
            .padding(.horizontal, DS.sm)
            .padding(.vertical, 5)
            .background(
                isSelected
                    ? Color.accentColor.opacity(0.08)
                    : Color.clear
            )
            .clipShape(RoundedRectangle(cornerRadius: 5))
        }
        .buttonStyle(.plain)
    }

    private func sidebarFolder(_ folder: DreamFileNode) -> some View {
        DisclosureGroup {
            ForEach(folder.children) { child in
                if let file = child.file {
                    sidebarItem(file: file)
                        .padding(.leading, DS.sm)
                }
            }
        } label: {
            Text(folder.name)
                .font(.system(size: 11, weight: .medium))
                .foregroundStyle(.tertiary)
                .textCase(.uppercase)
                .tracking(0.3)
                .padding(.top, DS.md)
                .padding(.bottom, DS.xs)
        }
        .padding(.horizontal, DS.sm)
    }

    // MARK: - Editor (Bear-style: clean, warm, text-first)

    private var editor: some View {
        VStack(spacing: 0) {
            if let file = selectedFile {
                // Floating toolbar — appears on hover (Bear-style)
                editorToolbar(file: file)
                    .opacity(isToolbarVisible || isDirty ? 1 : 0)
                    .animation(.easeInOut(duration: 0.15), value: isToolbarVisible)

                // The text
                ScrollView {
                    VStack(alignment: .leading, spacing: 0) {
                        // Title derived from first # heading or filename
                        Text(editorTitle(file: file))
                            .font(.system(size: 22, weight: .semibold))
                            .foregroundStyle(.primary)
                            .padding(.bottom, DS.sm)
                            .textSelection(.enabled)

                        if file.isAutoGenerated {
                            HStack(spacing: DS.xs) {
                                Image(systemName: "sparkles")
                                    .font(.system(size: 9))
                                Text("Auto-generated by Dream · updates every 60s")
                                    .font(.system(size: 11))
                            }
                            .foregroundStyle(.quaternary)
                            .padding(.bottom, DS.md)
                        }

                        // Editor
                        TextEditor(text: $editorContent)
                            .font(.system(size: 14, design: .default))
                            .scrollContentBackground(.hidden)
                            .lineSpacing(4)
                            .frame(minHeight: 400)
                            .onChange(of: editorContent) { _, _ in
                                isDirty = true
                            }
                    }
                    .padding(.horizontal, DS.xxl)
                    .padding(.top, DS.xl)
                    .padding(.bottom, 60)
                }
                .onHover { hovering in
                    isToolbarVisible = hovering
                }
            } else {
                emptyEditor
            }
        }
        .background(Color(.textBackgroundColor))
    }

    private func editorToolbar(file: DreamFile) -> some View {
        HStack(spacing: DS.md) {
            Text(file.name)
                .font(.system(size: 11))
                .foregroundStyle(.quaternary)

            Text(file.sizeFormatted)
                .font(.system(size: 10, design: .monospaced))
                .foregroundStyle(.quaternary)

            Spacer()

            if isDirty {
                Text("Edited")
                    .font(.system(size: 10))
                    .foregroundStyle(.orange.opacity(0.7))
            }

            Button {
                saveFile()
            } label: {
                Text("Save")
                    .font(.system(size: 11, weight: .medium))
            }
            .buttonStyle(.plain)
            .foregroundStyle(isDirty ? Color.accentColor : .quaternary)
            .disabled(!isDirty)
            .keyboardShortcut("s", modifiers: .command)
        }
        .padding(.horizontal, DS.xxl)
        .padding(.vertical, DS.sm)
    }

    private var emptyEditor: some View {
        VStack(spacing: DS.lg) {
            Image(systemName: "doc.text")
                .font(.system(size: 32, weight: .thin))
                .foregroundStyle(.quaternary)

            VStack(spacing: DS.xs) {
                Text("Select a file")
                    .font(.system(size: 15, weight: .medium))
                    .foregroundStyle(.tertiary)

                Text("Edit me.md to tell AI who you are.\nCreate notes for extra context.")
                    .font(.system(size: 12))
                    .foregroundStyle(.quaternary)
                    .multilineTextAlignment(.center)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Color(.textBackgroundColor))
    }

    // MARK: - New Note Sheet

    private var newNoteSheet: some View {
        VStack(alignment: .leading, spacing: DS.lg) {
            Text("New Note")
                .font(.system(size: 15, weight: .semibold))

            TextField("Name", text: $newNoteName)
                .textFieldStyle(.roundedBorder)
                .font(.system(size: 14))

            Text("Saved to ~/Dream/notes/\(sanitizedName).md")
                .font(.system(size: 11))
                .foregroundStyle(.tertiary)

            HStack {
                Button("Cancel") {
                    showNewNote = false
                    newNoteName = ""
                }
                .keyboardShortcut(.cancelAction)

                Spacer()

                Button("Create") {
                    createNote()
                }
                .buttonStyle(.borderedProminent)
                .keyboardShortcut(.defaultAction)
                .disabled(newNoteName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
            }
        }
        .padding(DS.xl)
        .frame(width: 300)
    }

    private var sanitizedName: String {
        newNoteName.trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: " ", with: "-")
            .lowercased()
    }

    // MARK: - Helpers

    private func displayName(_ name: String) -> String {
        switch name {
        case "me.md": return "About Me"
        case "now.md": return "Current Context"
        case "full.md": return "Full Context"
        case "MEMORY.md": return "Memory Index"
        default: return name.replacingOccurrences(of: ".md", with: "")
        }
    }

    private func fileAccent(_ name: String) -> Color {
        switch name {
        case "me.md": return .blue
        case "now.md": return .green
        case "full.md": return .purple
        case "MEMORY.md": return .orange
        default: return .secondary.opacity(0.5)
        }
    }

    private func editorTitle(file: DreamFile) -> String {
        // Extract first # heading from content
        let firstLine = editorContent.components(separatedBy: "\n").first ?? ""
        if firstLine.hasPrefix("# ") {
            return String(firstLine.dropFirst(2))
        }
        return displayName(file.name)
    }

    // MARK: - Data

    private var coreFiles: [DreamFile] {
        let coreNames = ["me.md", "now.md", "full.md", "MEMORY.md"]
        return coreNames.compactMap { name in
            let url = dreamDir.appendingPathComponent(name)
            guard FileManager.default.fileExists(atPath: url.path) else { return nil }
            let attrs = try? FileManager.default.attributesOfItem(atPath: url.path)
            return DreamFile(
                name: name,
                url: url,
                size: attrs?[.size] as? Int64 ?? 0,
                modified: attrs?[.modificationDate] as? Date ?? Date(),
                isAutoGenerated: true
            )
        }
    }

    private var folders: [DreamFileNode] {
        fileTree.filter(\.isDirectory)
    }

    // MARK: - File Operations

    private func refreshFileTree() {
        fileTree = scanDirectory(dreamDir)
    }

    private func selectFile(_ file: DreamFile) {
        if isDirty { saveFile() }
        selectedFile = file
        editorContent = (try? String(contentsOf: file.url, encoding: .utf8)) ?? ""
        isDirty = false
    }

    private func saveFile() {
        guard let file = selectedFile else { return }
        try? editorContent.write(to: file.url, atomically: true, encoding: .utf8)
        isDirty = false
    }

    private func createNote() {
        let name = sanitizedName
        guard !name.isEmpty else { return }

        let notesDir = dreamDir.appendingPathComponent("notes")
        try? FileManager.default.createDirectory(at: notesDir, withIntermediateDirectories: true)

        let fileName = name.hasSuffix(".md") ? name : "\(name).md"
        let filePath = notesDir.appendingPathComponent(fileName)
        let content = "# \(newNoteName.trimmingCharacters(in: .whitespacesAndNewlines))\n\n"

        try? content.write(to: filePath, atomically: true, encoding: .utf8)
        showNewNote = false
        newNoteName = ""
        refreshFileTree()

        selectFile(DreamFile(
            name: fileName, url: filePath,
            size: Int64(content.utf8.count), modified: Date(),
            isAutoGenerated: false
        ))
    }

    private func scanDirectory(_ url: URL) -> [DreamFileNode] {
        let fm = FileManager.default
        guard let contents = try? fm.contentsOfDirectory(
            at: url,
            includingPropertiesForKeys: [.isDirectoryKey, .fileSizeKey, .contentModificationDateKey],
            options: [.skipsHiddenFiles]
        ) else { return [] }

        let coreNames = Set(["me.md", "now.md", "full.md", "MEMORY.md"])
        var nodes: [DreamFileNode] = []

        let sorted = contents.sorted { $0.lastPathComponent < $1.lastPathComponent }

        for item in sorted {
            let values = try? item.resourceValues(forKeys: [.isDirectoryKey, .fileSizeKey, .contentModificationDateKey])
            let isDir = values?.isDirectory ?? false
            let name = item.lastPathComponent

            // Skip core files (shown separately at top)
            if !isDir && coreNames.contains(name) { continue }

            if isDir {
                let children = scanDirectory(item)
                    .flatMap { node -> [DreamFileNode] in
                        if node.isDirectory { return node.children }
                        return [node]
                    }
                if !children.isEmpty {
                    nodes.append(DreamFileNode(
                        name: name,
                        isDirectory: true,
                        file: nil,
                        children: children
                    ))
                }
            } else if name.hasSuffix(".md") {
                let file = DreamFile(
                    name: name,
                    url: item,
                    size: Int64(values?.fileSize ?? 0),
                    modified: values?.contentModificationDate ?? Date(),
                    isAutoGenerated: false
                )
                nodes.append(DreamFileNode(
                    name: name,
                    isDirectory: false,
                    file: file,
                    children: []
                ))
            }
        }

        return nodes
    }
}

// MARK: - Data Types

struct DreamFile: Identifiable {
    let name: String
    let url: URL
    let size: Int64
    let modified: Date
    let isAutoGenerated: Bool

    var id: String { url.path }
    var path: String { url.path }

    var sizeFormatted: String {
        ByteCountFormatter.string(fromByteCount: size, countStyle: .file)
    }
}

struct DreamFileNode: Identifiable {
    let name: String
    let isDirectory: Bool
    let file: DreamFile?
    let children: [DreamFileNode]

    var id: String { name + (isDirectory ? "/" : "") + (file?.path ?? "") }
}
