import SwiftUI

/// Files tab — Bear-inspired markdown viewer/editor.
struct FilesTab: View {
    @EnvironmentObject var appState: AppState
    @State private var selectedFile: WhatlyFile?
    @State private var fileTree: [WhatlyFileNode] = []
    @State private var editorContent: String = ""
    @State private var isDirty = false

    @State private var showNewFile = false
    @State private var showNewFolder = false
    @State private var showRename = false
    @State private var showDeleteConfirm = false
    @State private var dialogName = ""
    @State private var dialogParentDir = ""

    private let whatlyDir = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent("Whatly")

    var body: some View {
        NavigationSplitView {
            sidebar
                .navigationSplitViewColumnWidth(min: 190, ideal: 220, max: 280)
        } detail: {
            editor
        }
        .onAppear { refreshFileTree() }
        .sheet(isPresented: $showNewFile) { dialogSheet(title: "New File", placeholder: "filename", hint: hintPath(".md"), action: "Create") { createFile() } }
        .sheet(isPresented: $showNewFolder) { dialogSheet(title: "New Folder", placeholder: "folder name", hint: hintPath("/"), action: "Create") { createFolder() } }
        .sheet(isPresented: $showRename) { dialogSheet(title: "Rename", placeholder: "new name", hint: "\(sanitized(dialogName)).md", action: "Rename") { renameFile() } }
        .confirmationDialog("Delete this file?", isPresented: $showDeleteConfirm) {
            Button("Delete", role: .destructive) { deleteSelectedFile() }
        } message: { Text("Delete \"\(selectedFile?.name ?? "")\"? This cannot be undone.") }
    }

    private func hintPath(_ suffix: String) -> String {
        dialogParentDir.isEmpty ? "~/Whatly/\(sanitized(dialogName))\(suffix)" : "~/Whatly/\(dialogParentDir)/\(sanitized(dialogName))\(suffix)"
    }

    // MARK: - Sidebar

    private var sidebar: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Header
            HStack {
                Text("Whatly")
                    .font(.system(size: 12, weight: .semibold))
                    .foregroundStyle(.tertiary)
                Spacer()
                HStack(spacing: DS.sm) {
                    sidebarButton(icon: "doc.badge.plus", help: "New File") { showNewFileDialog(parent: "") }
                    sidebarButton(icon: "folder.badge.plus", help: "New Folder") { showNewFolderDialog(parent: "") }
                    sidebarButton(icon: "arrow.clockwise", help: "Refresh") { refreshFileTree() }
                    sidebarButton(icon: "folder", help: "Finder") { NSWorkspace.shared.open(whatlyDir) }
                }
            }
            .padding(.horizontal, DS.md)
            .padding(.vertical, DS.sm)

            Divider()

            // Files
            List(selection: Binding(
                get: { selectedFile?.path },
                set: { path in
                    if let path, let file = findFile(path: path) { selectFile(file) }
                }
            )) {
                // Core files
                Section {
                    ForEach(coreFiles, id: \.path) { file in
                        sidebarRow(file: file)
                            .tag(file.path)
                    }
                }

                // Folders
                ForEach(folders, id: \.name) { folder in
                    Section(folder.name.uppercased()) {
                        ForEach(folder.children, id: \.id) { child in
                            if let file = child.file {
                                sidebarRow(file: file)
                                    .tag(file.path)
                            }
                        }
                    }
                }
            }
            .listStyle(.sidebar)
        }
        .background(Color(.controlBackgroundColor).opacity(0.3))
    }

    private func sidebarButton(icon: String, help: String, action: @escaping () -> Void) -> some View {
        Button(action: action) {
            Image(systemName: icon).font(.system(size: 11))
        }
        .buttonStyle(.plain)
        .foregroundStyle(.tertiary)
        .help(help)
    }

    private func sidebarRow(file: WhatlyFile) -> some View {
        HStack(spacing: DS.sm) {
            Circle()
                .fill(fileAccent(file.name))
                .frame(width: 6, height: 6)

            Text(displayName(file.name))
                .font(DS.bodyFont)
                .lineLimit(1)

            Spacer()

            if file.isAutoGenerated {
                Circle()
                    .fill(Color.accentColor.opacity(0.3))
                    .frame(width: 4, height: 4)
            }
        }
        .contextMenu { fileContextMenu(file: file) }
    }

    // MARK: - Context Menu

    @ViewBuilder
    private func fileContextMenu(file: WhatlyFile) -> some View {
        Button("Open in Finder") { NSWorkspace.shared.activateFileViewerSelecting([file.url]) }
        if !file.isAutoGenerated {
            Divider()
            Button("Rename...") {
                dialogName = file.name.replacingOccurrences(of: ".md", with: "")
                showRename = true
            }
            Button("Delete", role: .destructive) {
                selectedFile = file
                showDeleteConfirm = true
            }
        }
        Divider()
        Button("Copy Path") {
            NSPasteboard.general.clearContents()
            NSPasteboard.general.setString(file.url.path, forType: .string)
        }
        Button("Copy Content") {
            if let content = try? String(contentsOf: file.url, encoding: .utf8) {
                NSPasteboard.general.clearContents()
                NSPasteboard.general.setString(content, forType: .string)
            }
        }
    }

    // MARK: - Editor

    private var editor: some View {
        Group {
            if let file = selectedFile {
                VStack(alignment: .leading, spacing: 0) {
                    // Toolbar
                    HStack(spacing: DS.md) {
                        Circle().fill(fileAccent(file.name)).frame(width: 8, height: 8)
                        Text(displayName(file.name))
                            .font(DS.titleFont)

                        if file.isAutoGenerated {
                            Text("auto")
                                .font(.system(size: 9, weight: .medium))
                                .foregroundStyle(.tertiary)
                                .padding(.horizontal, DS.xs)
                                .padding(.vertical, 1)
                                .background(Color.accentColor.opacity(0.08))
                                .clipShape(RoundedRectangle(cornerRadius: 3))
                        }

                        Spacer()

                        Text(file.sizeFormatted)
                            .font(DS.microFont)
                            .foregroundStyle(.quaternary)

                        if isDirty {
                            Text("Edited")
                                .font(DS.captionFont)
                                .foregroundStyle(.orange)
                        }

                        Button("Save") { saveFile() }
                            .buttonStyle(.borderedProminent)
                            .controlSize(.small)
                            .disabled(!isDirty)
                            .keyboardShortcut("s", modifiers: .command)
                    }
                    .padding(.horizontal, DS.xl)
                    .padding(.vertical, DS.sm)

                    Divider()

                    // Editor
                    TextEditor(text: $editorContent)
                        .font(.system(size: 14))
                        .scrollContentBackground(.hidden)
                        .lineSpacing(4)
                        .padding(.horizontal, DS.lg)
                        .padding(.top, DS.md)
                        .onChange(of: editorContent) { _, _ in isDirty = true }
                }
                .background(Color(.textBackgroundColor))
            } else {
                VStack(spacing: DS.lg) {
                    Image(systemName: "doc.text")
                        .font(.system(size: 32, weight: .thin))
                        .foregroundStyle(.quaternary)
                    Text("Select a file")
                        .font(DS.titleFont)
                        .foregroundStyle(.tertiary)
                    Text("Edit me.md to tell AI who you are\nCreate notes for extra context")
                        .font(DS.captionFont)
                        .foregroundStyle(.quaternary)
                        .multilineTextAlignment(.center)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Color(.textBackgroundColor))
            }
        }
    }

    // MARK: - Dialog Sheet

    private func dialogSheet(title: String, placeholder: String, hint: String, action: String, onSubmit: @escaping () -> Void) -> some View {
        VStack(alignment: .leading, spacing: DS.md) {
            Text(title).font(DS.titleFont)
            TextField(placeholder, text: $dialogName)
                .textFieldStyle(.roundedBorder)
                .onSubmit { onSubmit() }
            Text(hint).font(DS.captionFont).foregroundStyle(.tertiary)
            HStack {
                Button("Cancel") { dismissDialogs() }.keyboardShortcut(.cancelAction)
                Spacer()
                Button(action) { onSubmit() }
                    .buttonStyle(.borderedProminent)
                    .keyboardShortcut(.defaultAction)
                    .disabled(dialogName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
            }
        }
        .padding(DS.xl)
        .frame(width: 300)
    }

    // MARK: - File Operations

    private func showNewFileDialog(parent: String) { dialogParentDir = parent; dialogName = ""; showNewFile = true }
    private func showNewFolderDialog(parent: String) { dialogParentDir = parent; dialogName = ""; showNewFolder = true }
    private func dismissDialogs() { showNewFile = false; showNewFolder = false; showRename = false; dialogName = ""; dialogParentDir = "" }

    private func createFile() {
        let name = sanitized(dialogName)
        guard !name.isEmpty else { return }
        let dir = dialogParentDir.isEmpty ? whatlyDir : whatlyDir.appendingPathComponent(dialogParentDir)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let fileName = name.hasSuffix(".md") ? name : "\(name).md"
        let filePath = dir.appendingPathComponent(fileName)
        let content = "# \(dialogName.trimmingCharacters(in: .whitespacesAndNewlines))\n\n"
        try? content.write(to: filePath, atomically: true, encoding: .utf8)
        dismissDialogs()
        refreshFileTree()
        selectFile(WhatlyFile(name: fileName, url: filePath, size: Int64(content.utf8.count), modified: Date(), isAutoGenerated: false))
    }

    private func createFolder() {
        let name = sanitized(dialogName)
        guard !name.isEmpty else { return }
        let path = whatlyDir.appendingPathComponent(name)
        try? FileManager.default.createDirectory(at: path, withIntermediateDirectories: true)
        try? "# \(dialogName.trimmingCharacters(in: .whitespacesAndNewlines))\n".write(to: path.appendingPathComponent("readme.md"), atomically: true, encoding: .utf8)
        dismissDialogs()
        refreshFileTree()
    }

    private func renameFile() {
        guard let file = selectedFile, !file.isAutoGenerated else { return }
        let name = sanitized(dialogName)
        guard !name.isEmpty else { return }
        let fileName = name.hasSuffix(".md") ? name : "\(name).md"
        let newURL = file.url.deletingLastPathComponent().appendingPathComponent(fileName)
        try? FileManager.default.moveItem(at: file.url, to: newURL)
        dismissDialogs()
        refreshFileTree()
        selectFile(WhatlyFile(name: fileName, url: newURL, size: file.size, modified: Date(), isAutoGenerated: false))
    }

    private func deleteSelectedFile() {
        guard let file = selectedFile, !file.isAutoGenerated else { return }
        try? FileManager.default.removeItem(at: file.url)
        selectedFile = nil; editorContent = ""; isDirty = false
        refreshFileTree()
    }

    private func selectFile(_ file: WhatlyFile) {
        if isDirty { saveFile() }
        selectedFile = file
        editorContent = (try? String(contentsOf: file.url, encoding: .utf8)) ?? ""
        isDirty = false
    }

    private func saveFile() {
        guard let file = selectedFile else { return }
        try? editorContent.write(to: file.url, atomically: true, encoding: .utf8)
        isDirty = false
    }

    // MARK: - Helpers

    private func sanitized(_ name: String) -> String {
        name.trimmingCharacters(in: .whitespacesAndNewlines).replacingOccurrences(of: " ", with: "-").lowercased()
    }

    private func displayName(_ name: String) -> String {
        switch name {
        case "me.md": "About Me"
        case "now.md": "Current Context"
        case "full.md": "Full Context"
        case "MEMORY.md": "Memory Index"
        default: name.replacingOccurrences(of: ".md", with: "").replacingOccurrences(of: "-", with: " ").capitalized
        }
    }

    private func fileAccent(_ name: String) -> Color {
        switch name {
        case "me.md": .blue
        case "now.md": .green
        case "full.md": .purple
        case "MEMORY.md": .orange
        default: .secondary.opacity(0.5)
        }
    }

    private func findFile(path: String) -> WhatlyFile? {
        if let core = coreFiles.first(where: { $0.path == path }) { return core }
        for folder in folders {
            if let child = folder.children.first(where: { $0.file?.path == path }) { return child.file }
        }
        return nil
    }

    private var coreFiles: [WhatlyFile] {
        ["me.md", "now.md", "full.md", "MEMORY.md"].compactMap { name in
            let url = whatlyDir.appendingPathComponent(name)
            guard FileManager.default.fileExists(atPath: url.path) else { return nil }
            let attrs = try? FileManager.default.attributesOfItem(atPath: url.path)
            return WhatlyFile(name: name, url: url, size: attrs?[.size] as? Int64 ?? 0, modified: attrs?[.modificationDate] as? Date ?? Date(), isAutoGenerated: true)
        }
    }

    private var folders: [WhatlyFileNode] { fileTree.filter(\.isDirectory) }

    private func refreshFileTree() { fileTree = scanDirectory(whatlyDir) }

    private func scanDirectory(_ url: URL) -> [WhatlyFileNode] {
        let fm = FileManager.default
        guard let contents = try? fm.contentsOfDirectory(at: url, includingPropertiesForKeys: [.isDirectoryKey, .fileSizeKey, .contentModificationDateKey], options: [.skipsHiddenFiles]) else { return [] }
        let coreNames = Set(["me.md", "now.md", "full.md", "MEMORY.md"])
        var nodes: [WhatlyFileNode] = []
        for item in contents.sorted(by: { $0.lastPathComponent < $1.lastPathComponent }) {
            let values = try? item.resourceValues(forKeys: [.isDirectoryKey, .fileSizeKey, .contentModificationDateKey])
            let isDir = values?.isDirectory ?? false
            let name = item.lastPathComponent
            if !isDir && coreNames.contains(name) { continue }
            if isDir {
                let children = scanDirectory(item).flatMap { $0.isDirectory ? $0.children : [$0] }
                if !children.isEmpty { nodes.append(WhatlyFileNode(name: name, isDirectory: true, file: nil, children: children)) }
            } else if name.hasSuffix(".md") {
                let file = WhatlyFile(name: name, url: item, size: Int64(values?.fileSize ?? 0), modified: values?.contentModificationDate ?? Date(), isAutoGenerated: false)
                nodes.append(WhatlyFileNode(name: name, isDirectory: false, file: file, children: []))
            }
        }
        return nodes
    }
}

// MARK: - Data Types

struct WhatlyFile: Identifiable, Hashable {
    let name: String
    let url: URL
    let size: Int64
    let modified: Date
    let isAutoGenerated: Bool
    var id: String { url.path }
    var path: String { url.path }
    var sizeFormatted: String { ByteCountFormatter.string(fromByteCount: size, countStyle: .file) }
    func hash(into hasher: inout Hasher) { hasher.combine(url.path) }
    static func == (lhs: WhatlyFile, rhs: WhatlyFile) -> Bool { lhs.url.path == rhs.url.path }
}

struct WhatlyFileNode: Identifiable {
    let name: String
    let isDirectory: Bool
    let file: WhatlyFile?
    let children: [WhatlyFileNode]
    var id: String { name + (isDirectory ? "/" : "") + (file?.path ?? "") }
}
